### ISSUE TITLE
+ %prefix% für custom Warp-Message

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/RedWarps#3]
Das Plugin funktioniert schonmal gut. :) Wenn du den Platzhalter %prefix% bei den Custom-Nachrichten der Warps hinzufügst, wäre das super.

(`prefix` aus Config.yml)

```
test:
  aliases:
  - t1
  world: world
  x: -3.320683087345383
  y: 63.0
  z: -85.5348530936276
  yaw: -30.597198
  pitch: 8.100018
  permission: rwm.redwarps.warp.test
  message: "%prefix% test"
  commands:
  - list
```

Den Abschnitt `  message: ''` kannst du auch gerne bei jedem neuen Warp mit in die Config schreiben. Momentan wird das ausgelassen.
